name: '🎛️ Atualizar Versão'
description: 'Atualiza a versão do módulo e realiza um commit.'
inputs:
  version:
    description: 'Nova versão para ser definida no módulo.'
    required: true
  github_token:
    description: 'Token para clonar workspace'
    required: true 
runs:
  using: 'composite'
  steps:
    - name: 'Check Github Token'
      run: |
        if [ -z "${{ inputs.github_token }}" ]; then
          echo "GitHub Token não fornecido."
          exit 1
        else
          echo "GitHub Token está presente."
        fi
      shell: bash

    - name: 'Input Vars Verification'
      run: |
        if [ -z "${{ inputs.version }}" ]; then
          echo "Versão não fornecida."
          exit 1
        else
          echo "Versão fornecida: ${{ inputs.version }}"
        fi
      shell: bash

    - name: 'Github Repository Triggered by'
      run: |
        REPO_NAME=$(basename "${{ github.repository }}")
        echo "O nome do repositório que disparou a action é: $REPO_NAME"
        echo "repo_name=$REPO_NAME" >> $GITHUB_ENV
      shell: bash

    - name: 'Is a Core?'
      run: |
        IS_CORE=$([[ "$GITHUB_REPOSITORY" == "GEDPaciente/mv-ged-core" || "$GITHUB_REPOSITORY" == "GEDPaciente/mv-gap-core" ]] && echo true || echo false)
        echo "É um core? $IS_CORE"
        echo "is_core=$IS_CORE" >> $GITHUB_ENV
      shell: bash

    - name: 'Checkout Repositório Parent'
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
        repository: GEDPaciente/mv-ged-parent
        token: ${{ inputs.github_token }}
        path: parent
        submodules: 'true'

    - name: 'Check prop to update'
      if: ${{ env.is_core == 'true' }}
      run: |
        repo_name=${{ env.repo_name }}
        if [[ "$GITHUB_REPOSITORY" == "GEDPaciente/mv-ged-core" ]]; then
          PROPERTY_NAME="ged.core.version"
        elif [[ "$GITHUB_REPOSITORY" == "GEDPaciente/mv-gap-core" ]]; then
          PROPERTY_NAME="ged.auth.core.version"
        else
          exit 0
        fi

        echo "Variavel para alteração: $PROPERTY_NAME"
        echo "PROPERTY_NAME=$PROPERTY_NAME" >> $GITHUB_ENV
      shell: bash

    - name: 'Compile module with new version'
      run: |
        cd parent

        git submodule update --init --recursive
        git submodule foreach git fetch origin
        git submodule foreach git pull origin ${{ github.ref_name }}

        cd ..
        
        cd parent/${{ env.repo_name }}
        
        mvn versions:set -DnewVersion=${{ inputs.version }} -q

        if [ -f package.json ]; then
          echo "Atualizando versão no package.json para ${{ inputs.version }}"
          jq --arg version "${{ inputs.version }}" '.version = $version' package.json > package.json.tmp
          mv package.json.tmp package.json
          git add package.json
        fi

        echo "Versão alterada do módulo"

        # Adicionar somente o pom.xml ao staging
        git add pom.xml

        # Configurar o usuário para o commit
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

        # Comitar as mudanças no pom.xml
        git commit -m "Atualização da versão para ${{ inputs.version }}"

        # Fazer pull antes de fazer push para evitar conflitos
        git pull origin ${{ github.ref_name }} --rebase

        # Fazer push da alteração para o repositório remoto
        git push origin HEAD:${{ env.repo_name }}

        echo "Versão atualizada e commitada para o módulo ${{ env.repo_name }}"

        cd ..
      shell: bash

    - name: 'Update version in parent'
      if: ${{ env.is_core == 'true' }}
      run: |
        cd parent

        git submodule update --init --recursive
        git submodule foreach git fetch origin
        git submodule foreach git pull origin ${{ github.ref_name }}

        PROPERTY_NAME=$(cat $GITHUB_ENV | grep PROPERTY_NAME | cut -d'=' -f2)
        mvn versions:update-property -Dproperty=$PROPERTY_NAME -DnewVersion=${{ inputs.version }} -q

        echo "Versão alterada da propriedade"

        # Adicionar somente o pom.xml ao staging
        git add pom.xml

        # Configurar o usuário para o commit
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

        # Comitar as mudanças no pom.xml
        git commit -m "Atualiza versão do $PROPERTY_NAME para ${{ inputs.version }}"

        # Fazer pull antes de fazer push para evitar conflitos
        git pull origin ${{ github.ref_name }} --rebase

        # Fazer push da alteração para o repositório remoto
        git push origin HEAD:${{ env.repo_name }}

        echo "Versão atualizada e commitada para o parent"
      shell: bash
