name: '🚀 Version Flow'

on:
  push:
    branches:
      - develop

jobs:
  version:
    name: 'Check version'
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.check-version.outputs.version }}
      release_branch: ${{ steps.check-version.outputs.release_branch }}
    steps:
      - uses: actions/checkout@v3
      - name: 'Check commit author'
        run: |
          COMMITTER=$(git log -1 --pretty=%an)
          if [ "$COMMITTER" == "action@github.com" ]; then
            echo "Commit feito por action@github.com, interrompendo o fluxo."
            exit 0
          fi
      - id: check-version
        uses: GEDPaciente/workflows/get-and-check-version@main
        with:
          release_branch: main
          github_token: ${{ secrets.GED_PAT }}

  compile:
    needs: version
    name: "Compile project"
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - id: compile
        uses: GEDPaciente/workflows/compile@develop
        with:
          github_token: ${{ secrets.GED_PAT }}

  update-version:
    needs: [version,compile]
    name: "Update Version"
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - id: compile
        uses: GEDPaciente/workflows/update-version@develop
        with:
          github_token: ${{ secrets.GED_PAT }}
          version: ${{ needs.version.outputs.version }}
