name: '🎛️ Module FLOW'
description: 'Fluxo de atualização do Modulo'
inputs:
  release_branch:
    description: 'Branch de release'
    required: true
  github_token:
    description: 'Token de acesso ao Github'
    required: true
  actual_branch:
    description: 'Branch atual'
    required: true
runs:
  using: 'composite'
  steps:
    - name: 🔒 Verificar GitHub Token
      run: |
        if [ -z "${{ inputs.github_token }}" ]; then
          echo "GitHub Token não fornecido."
          exit 1
        else
          echo "GitHub Token está presente."
        fi
      shell: bash

    - name: 🚚 Atualizando projeto
      uses: actions/checkout@v3
      with:
        repository: GEDPaciente/mv-ged-workspace
        token: ${{ inputs.github_token }}
        submodules: true
        ref: ${{ github.ref }}

    - name: 📝 MVN Build Workspace
      run: mvn clean install
      shell: bash

    - name: 📝 Obtem a Versão do workspace
      run: mvn help:evaluate -Dexpression=project.version -q -DforceStdout
      shell: bash
