name: '🎛️ Workspace FLOW'
description: 'Fluxo de atualização do workspace'
inputs:
  version:
    description: 'Nova versão para ser definida no pom.xml'
    required: true
runs:
  using: 'composite'
  steps:
    - name: 🚚 Checkout Project
      uses: actions/checkout@v3

    - name: Clone Submodules
      run: |
        git config --global url."https://x-access-token:${MY_GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
        git submodule update --init --recursive
      shell: bash

    - name: 📝 MVN Clean Install
      run: mvn clean install
      shell: bash

    - name: 📝 Obtem a Versão do workspace
      run: mvn help:evaluate -Dexpression=project.version -q -DforceStdout
      shell: bash
    
