name: '🎛️ Build Modulo'
description: 'Fluxo de atualização do Modulo'
inputs:
  github_token:
    description: 'Token de acesso ao GitHub'
    required: true
outputs:
  module_version:
    description: 'Versão do Modulo'
    value: ${{ steps.get_version.outputs.version }}
  core_version:
    description: 'Versão do GED-CORE'
    value: ${{ steps.build-core.outputs.core_version }}
runs:
  using: 'composite'
  steps:
    - name: 🔒 Verificar GitHub Token
      run: |
        if [ -z "${{ inputs.github_token }}" ]; then
          echo "GitHub Token não fornecido."
          exit 1
        else
          echo "GitHub Token está presente."
        fi
      shell: bash

    - name: 'Build Core'
      id: build-core
      uses: GEDPaciente/workflows/build-core@main
      with:
        github_token: ${{ inputs.github_token }}

    - name: 🚚 Atualizando projeto
      uses: actions/checkout@v3
      with:
        path: module

    - name: 'Set up JDK 17'
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '17'
        
    - name: 'Listing all folders'
      run: ls
      shell: bash
      
    - name: 'Altera versão do GED CORE do modulo'
      run: |
        cd module
        echo "Atualizando versão do GED CORE para $core_version"
        mvn versions:set-property -Dproperty="ged.core.version" -DnewVersion="$core_version" -DgenerateBackupPoms=false -B
      shell: bash
    
    - name: 'Verificar versão'
      id: get_version
      run: |
        CURRENT_VERSION=$(mvn help:evaluate -Dexpression="project.version" -q -DforceStdout)
        echo "Versão do Modulo: $CURRENT_VERSION"
        echo "module_version=$CURRENT_VERSION" >> $GITHUB_ENV
      shell: bash    

    - name: 'Build'
      run: mvn clean install -N -q
      shell: bash

    - name: 'Obtem versão atual do core no projeto'
      run: |
        VERSION=$(mvn help:evaluate -Dexpression="ged.core.version" -q -DforceStdout)

        echo "Versão do GED CORE: $VERSION"
        
        if [ -z "$VERSION" ]; then
          echo "Versão do GED CORE não encontrada."
          exit 1
        fi

        if [ "$VERSION" == "$core_version" ]; then
          echo "Versão do GED CORE já é $CORE_LATEST. Nenhuma atualização necessária."
          echo "skip_commit=true" >> $GITHUB_ENV
        fi

        echo "atual_core_version=$VERSION" >> $GITHUB_ENV
      shell: bash

    - name: Commit
      if: env.skip_commit != 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        git add pom.xml
        git commit -m "Atualiza versão do CORE para $core_version"
        git push
      shell: bash

    
