name: '🎛️ Build Modulo'
description: 'Fluxo de atualização do Modulo'
inputs:
  github_token:
    description: 'Token de acesso ao GitHub'
    required: true
outputs:
  module_version:
    description: 'Versão do Modulo'
    value: ${{ steps.get_version.outputs.version }}

runs:
  using: 'composite'
  steps:
    - name: 🔒 Verificar GitHub Token
      run: |
        if [ -z "${{ inputs.github_token }}" ]; then
          echo "GitHub Token não fornecido."
          exit 1
        else
          echo "GitHub Token está presente."
        fi
      shell: bash

    - name: 'Checkout Repositório Parent'
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
        repository: GEDPaciente/mv-ged-parent
        token: ${{ inputs.github_token }}
        path: parent

    - name: 'Set up JDK 17'
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '17'

    - name: 'Build Parent e Gerar JARs'
      run: |
        cd parent
        mvn clean package -DskipTests -q
        mkdir -p core/target
        cp mv-ged-core/target/*.jar core/target/
        cp mv-gap-core/target/*.jar core/target/
        echo "Arquivos JAR movidos para core/target"
        cp parent/$REPO_NAME module/
        echo "Arquivos do projeto movido para module"
        cd ..
      shell: bash

    