name: '🎛️ Build Parent com Submódulos'
description: '🚀 Realiza o build do Parent com GED-CORE e GAP-CORE'
inputs:
  github_token:
    description: 'Token de acesso ao GitHub'
    required: true
outputs:
  core_version:
    description: 'Versão do GED-CORE'
    value: ${{ steps.get_version_core.outputs.core_version }}
  gap_core_version:
    description: 'Versão do GAP-CORE'
    value: ${{ steps.get_version_gap.outputs.gap_core_version }}
runs:
  using: 'composite'
  steps:
    - name: 🔒 Verificar GitHub Token
      run: |
        if [ -z "${{ inputs.github_token }}" ]; then
          echo "GitHub Token não fornecido."
          exit 1
        else
          echo "GitHub Token está presente."
        fi
      shell: bash

    - name: 'Configurar Credenciais para Submódulos'
      run: |
        git config --global url."https://${{ inputs.github_token }}@github.com/".insteadOf "https://github.com/"
      shell: bash

    - name: 'Set up JDK 17'
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '17'

    - name: 'Checkout Repositório Parent na Mesma Ref'
      uses: actions/checkout@v3
      with:
        repository: GEDPaciente/mv-ged-parent
        token: ${{ inputs.github_token }}
        ref: ${{ github.ref }}
        path: parent

    - name: 'Atualizar e Inicializar Submódulo mv-ged-core'
      run: |
        echo "Inicializando e atualizando o submódulo mv-ged-core"
        cd parent
        git submodule update --init --recursive mv-ged-core
        cd mv-ged-core
        git fetch origin
        git pull origin main
        echo "Submódulo mv-ged-core atualizado"
        cd ../..
      shell: bash

    - name: 'Atualizar e Inicializar Submódulo mv-gap-core'
      run: |
        echo "Inicializando e atualizando o submódulo mv-gap-core"
        cd parent
        git submodule update --init --recursive mv-gap-core
        cd mv-gap-core
        git fetch origin
        git pull origin main
        echo "Submódulo mv-gap-core atualizado"
        cd ../..
      shell: bash

    - name: 'Verificar versão do GED-CORE no Parent'
      id: get_version_core
      run: |
        cd parent/mv-ged-core
        CORE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "Versão do GED-CORE: $CORE_VERSION"
        echo "core_version=$CORE_VERSION" >> $GITHUB_ENV
        cd ../..

        # Verifica e altera a versão no pom.xml do Parent se necessário
        cd parent
        PARENT_CORE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        if [ "$PARENT_CORE_VERSION" != "$CORE_VERSION" ]; then
          echo "Atualizando versão do GED-CORE no pom.xml do parent para $CORE_VERSION"
          mvn versions:set -DnewVersion=$CORE_VERSION
          git add pom.xml
          git commit -m "Atualiza versão do GED-CORE para $CORE_VERSION no parent"
        fi
        cd ..
      shell: bash

    - name: 'Verificar versão do GAP-CORE no Parent'
      id: get_version_gap
      run: |
        cd parent/mv-gap-core
        GAP_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "Versão do GAP-CORE: $GAP_VERSION"
        echo "gap_core_version=$GAP_VERSION" >> $GITHUB_ENV
        cd ../..

        # Verifica e altera a versão no pom.xml do Parent se necessário
        cd parent
        PARENT_GAP_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        if [ "$PARENT_GAP_VERSION" != "$GAP_VERSION" ]; then
          echo "Atualizando versão do GAP-CORE no pom.xml do parent para $GAP_VERSION"
          mvn versions:set -DnewVersion=$GAP_VERSION
          git add pom.xml
          git commit -m "Atualiza versão do GAP-CORE para $GAP_VERSION no parent"
        fi
        cd ..
      shell: bash

    - name: 'Build Parent com Submódulos'
      run: |
        echo "Iniciando build do parent com GED-CORE e GAP-CORE"
        cd parent
        mvn clean install -pl mv-ged-core,mv-gap-core -am -q
        echo "Build do parent concluído com GED-CORE e GAP-CORE"
        cd ..
      shell: bash

    - name: 'Comitar alterações no pom.xml se necessário'
      run: |
        cd parent
        if [ -n "$(git status --porcelain)" ]; then
          echo "Alterações detectadas, comitando."
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Atualiza versões dos submódulos no pom.xml"
          git push origin ${{ github.ref }}
        else
          echo "Nenhuma alteração no pom.xml"
        fi
        cd ..
      shell: bash
