name: '🎛️ Build Parent com Submódulos'
description: '🚀 Realiza o build do Parent com GED-CORE e GAP-CORE'
inputs:
  github_token:
    description: 'Token de acesso ao GitHub'
    required: true
outputs:
  core_version:
    description: 'Versão do GED-CORE'
    value: ${{ steps.get_version_core.outputs.core_version }}
  gap_core_version:
    description: 'Versão do GAP-CORE'
    value: ${{ steps.get_version_gap.outputs.gap_core_version }}
runs:
  using: 'composite'
  steps:
    - name: 🔒 Verificar GitHub Token
      run: |
        if [ -z "${{ inputs.github_token }}" ]; then
          echo "GitHub Token não fornecido."
          exit 1
        else
          echo "GitHub Token está presente."
        fi
      shell: bash

    - name: 'Configurar Credenciais para Submódulos'
      run: |
        git config --global url."https://${{ inputs.github_token }}@github.com/".insteadOf "https://github.com/"
      shell: bash

    - name: 'Set up JDK 17'
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '17'

    - name: 'Checkout Parent Repository com Submódulos'
      uses: actions/checkout@v3
      with:
        repository: GEDPaciente/mv-ged-parent
        token: ${{ inputs.github_token }}
        path: parent

    - name: 'Atualizar e Inicializar Submódulo mv-ged-core'
      run: |
        echo "Inicializando e atualizando o submódulo mv-ged-core"
        cd parent
        git submodule update --init --recursive mv-ged-core
        cd mv-ged-core
        git fetch origin
        git pull origin main
        echo "Submódulo mv-ged-core atualizado"
        cd ../..
      shell: bash

    - name: 'Atualizar e Inicializar Submódulo mv-gap-core'
      run: |
        echo "Inicializando e atualizando o submódulo mv-gap-core"
        cd parent
        git submodule update --init --recursive mv-gap-core
        cd mv-gap-core
        git fetch origin
        git pull origin main
        echo "Submódulo mv-gap-core atualizado"
        cd ../..
      shell: bash

    - name: 'Build Parent com Submódulos'
      run: |
        echo "Iniciando build do parent com GED-CORE e GAP-CORE"
        cd parent
        mvn clean install -pl mv-ged-core,mv-gap-core -am -q
        echo "Build do parent concluído com GED-CORE e GAP-CORE"
        cd ..
      shell: bash

    - name: 'Verificar versão do GED-CORE'
      id: get_version_core
      run: |
        cd parent/mv-ged-core
        CORE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "Versão do GED-CORE: $CORE_VERSION"
        echo "core_version=$CORE_VERSION" >> $GITHUB_ENV
        cd ../..
      shell: bash

    - name: 'Verificar versão do GAP-CORE'
      id: get_version_gap
      run: |
        cd parent/mv-gap-core
        GAP_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "Versão do GAP-CORE: $GAP_VERSION"
        echo "gap_core_version=$GAP_VERSION" >> $GITHUB_ENV
        cd ../..
      shell: bash
