name: '🎛️ Build Core'
description: '🚀 Realiza o build do GED-CORE'
inputs:
  github_token:
    description: 'Token de acesso ao GitHub'
    required: true
outputs:
  core_version:
    description: 'Versão do GED-CORE'
    value: ${{ steps.get_version.outputs.core_version }}
  gap_core_version:
    description: 'Versão do GAP-CORE'
    value: ${{ steps.get_gap_version.outputs.gap_core_version }}
runs:
  using: 'composite'
  steps:
    - name: 🔒 Verificar GitHub Token
      run: |
        if [ -z "${{ inputs.github_token }}" ]; then
          echo "GitHub Token não fornecido."
          exit 1
        else
          echo "GitHub Token está presente."
        fi
      shell: bash

    - name: 'Configurar Credenciais para Submódulos'
      run: |
        git config --global url."https://${{ inputs.github_token }}@github.com/".insteadOf "https://github.com/"
      shell: bash

    - name: 'Checkout Parent Repository com Submódulos'
      uses: actions/checkout@v3
      with:
        repository: GEDPaciente/mv-ged-parent
        token: ${{ inputs.github_token }}
        path: parent

    - name: 'Set up JDK 17'
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '17'
       
    - name: 'Detectar Branch do Repositório'
      id: detect_branch
      run: |
        BRANCH_NAME=$(echo "${{ github.ref }}" | sed -E 's|refs/heads/||')
        echo "Branch detectada: $BRANCH_NAME"
        echo "branch_name=$BRANCH_NAME" >> $GITHUB_ENV
      shell: bash

    - name: 'Inicializar e Atualizar Submódulo mv-ged-core'
      run: |
        echo "Inicializando e atualizando o submódulo mv-ged-core"
        cd parent
        git submodule update --init --recursive mv-ged-core
        cd mv-ged-core
        git fetch origin # Garante que todas as branches remotas sejam buscadas
        git checkout -B ${{ env.branch_name }} origin/${{ env.branch_name }} || git checkout ${{ env.branch_name }}
        git pull
        echo "Submódulo mv-ged-core atualizado para a branch ${{ env.branch_name }}"
        cd ../..
      shell: bash

    - name: 'Forçar Falha'
      run: |
        echo "Forçando falha da action."
        exit 1
      shell: bash
