name: '🎛️ Build Core'
description: '🚀 Realiza o build do GED-CORE'
inputs:
  github_token:
    description: 'Token de acesso ao GitHub'
    required: true
runs:
  using: 'composite'
  steps:
    - name: 🔒 Verificar GitHub Token
      run: |
        if [ -z "${{ inputs.github_token }}" ]; then
          echo "GitHub Token não fornecido."
          exit 1
        else
          echo "GitHub Token está presente."
        fi
      shell: bash

    - name: 'Checkout Repository'
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
        repository: GEDPaciente/mv-ged-core
        token: ${{ inputs.github_token }}
          
    - name: 'Set up JDK 17'
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '17'
        
    - name: 'Build'
      run: |
        cd workspace
        mvn clean install -N
        cd ..
      shell: bash